@startuml
!include style.puml
skinparam ArrowFontStyle plain

' color to be update
participant ":MainApp" as MainApp SETUP_COLOR
[-> MainApp : start(Stage)
activate MainApp

' color to be update
participant ":Ui" as Ui UI_COLOR
MainApp -> Ui : start(Logic)
activate Ui

participant ":Logic" as Logic LOGIC_COLOR
Ui -> Logic : hasInitialError()
activate Logic
Ui <-- Logic
deactivate Logic

participant "FileUtil" as FileUtil <<class>> LOGIC_COLOR_T2
opt hasInitialError
Ui -> FileUtil : backupFile(filePath)
activate FileUtil

FileUtil -> FileUtil : getFileNameWithoutExt(filePath)
activate FileUtil
FileUtil --> FileUtil
deactivate FileUtil

FileUtil -> FileUtil : getFileExtension(filePath)
activate FileUtil
FileUtil --> FileUtil
deactivate FileUtil

participant "Files" as Files <<class>> LOGIC_COLOR_T2
' FileUtil -> Files : copy(Source, Target, Option)
FileUtil -> Files : copy()
activate Files
FileUtil <-- Files
deactivate Files
end

Ui <-- FileUtil
deactivate FileUtil

MainApp <-- Ui
deactivate Ui

[<-- MainApp 
deactivate MainApp
@enduml
