@startuml
!include style.puml
skinparam ArrowFontStyle plain

participant ":HideCommand" as HideCommand SETUP_COLOR
[-> HideCommand : execute(Model)
activate HideCommand

participant ":Model" as Model MODEL_COLOR
HideCommand -> Model : getFilteredPersonList()
activate Model

Model --> HideCommand : filteredPersons
deactivate Model

participant ":Person" as Person PERSON_COLOR
HideCommand -> Person : hideDetails()
activate Person
Person --> HideCommand
deactivate Person

participant ":CommandResult" as CommandResult COMMAND_RESULT_COLOR
create CommandResult
HideCommand -> CommandResult
activate CommandResult
CommandResult --> HideCommand
deactivate CommandResult

[<-- HideCommand
deactivate HideCommand
@enduml
